cool: out
	g++ -o ../out/client -I../common -pthread -std=c++17 -D COOL client.cpp ../common/json.cpp

rdm: out
	g++ -o ../out/client -I../common -pthread -std=c++17 client.cpp ../common/json.cpp

out:
	mkdir -p ../out