cool: out
	g++ -o ../out/mp -I../common -pthread -std=c++17 -D COOL mp.cpp ../common/json.cpp
rdm: out
	g++ -o ../out/mp -I../common -pthread -std=c++17 mp.cpp ../common/json.cpp

out:
	mkdir -p ../out