//
// Generated file, do not edit! Created by opp_msgtool 6.0 from LenMsg.msg.
//

#ifndef __LENMSG_M_H
#define __LENMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class LenMsg;
/**
 * Class generated from <tt>LenMsg.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet LenMsg
 * {
 *     int ID;
 *     int len;
 * }
 * </pre>
 */
class LenMsg : public ::omnetpp::cPacket
{
  protected:
    int ID = 0;
    int len = 0;

  private:
    void copy(const LenMsg& other);

  protected:
    bool operator==(const LenMsg&) = delete;

  public:
    LenMsg(const char *name=nullptr, short kind=0);
    LenMsg(const LenMsg& other);
    virtual ~LenMsg();
    LenMsg& operator=(const LenMsg& other);
    virtual LenMsg *dup() const override {return new LenMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getID() const;
    virtual void setID(int ID);

    virtual int getLen() const;
    virtual void setLen(int len);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LenMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LenMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline LenMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<LenMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __LENMSG_M_H

