//
// Generated file, do not edit! Created by opp_msgtool 6.0 from SourcedMsg.msg.
//

#ifndef __SOURCEDMSG_M_H
#define __SOURCEDMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SourcedMsg;
/**
 * Class generated from <tt>SourcedMsg.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message SourcedMsg
 * {
 *     int source;
 *     int ID;
 *     simtime_t time_send = -1;
 *     simtime_t time_in = -1;
 *     simtime_t time_queue = -1;
 *     simtime_t time_serv = -1;
 *     simtime_t time_out = -1;
 *     simtime_t time_recv = -1;
 * }
 * </pre>
 */
class SourcedMsg : public ::omnetpp::cMessage
{
  protected:
    int source = 0;
    int ID = 0;
    omnetpp::simtime_t time_send = -1;
    omnetpp::simtime_t time_in = -1;
    omnetpp::simtime_t time_queue = -1;
    omnetpp::simtime_t time_serv = -1;
    omnetpp::simtime_t time_out = -1;
    omnetpp::simtime_t time_recv = -1;

  private:
    void copy(const SourcedMsg& other);

  protected:
    bool operator==(const SourcedMsg&) = delete;

  public:
    SourcedMsg(const char *name=nullptr, short kind=0);
    SourcedMsg(const SourcedMsg& other);
    virtual ~SourcedMsg();
    SourcedMsg& operator=(const SourcedMsg& other);
    virtual SourcedMsg *dup() const override {return new SourcedMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual int getID() const;
    virtual void setID(int ID);

    virtual omnetpp::simtime_t getTime_send() const;
    virtual void setTime_send(omnetpp::simtime_t time_send);

    virtual omnetpp::simtime_t getTime_in() const;
    virtual void setTime_in(omnetpp::simtime_t time_in);

    virtual omnetpp::simtime_t getTime_queue() const;
    virtual void setTime_queue(omnetpp::simtime_t time_queue);

    virtual omnetpp::simtime_t getTime_serv() const;
    virtual void setTime_serv(omnetpp::simtime_t time_serv);

    virtual omnetpp::simtime_t getTime_out() const;
    virtual void setTime_out(omnetpp::simtime_t time_out);

    virtual omnetpp::simtime_t getTime_recv() const;
    virtual void setTime_recv(omnetpp::simtime_t time_recv);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SourcedMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SourcedMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SourcedMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<SourcedMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SOURCEDMSG_M_H

